### ISSUE TITLE
Missing TLS Step (Part 1)

### ISSUE THREAD

**Issue by PeggySchmidtMittenzwei** [exasol/exasol-java-tutorial#19]
I copied my ca.crt to Exasol-DB

pesm@pesm-VirtualBox:~/tutorials/tls_with_exasol/import$ docker cp "ca.crt" exasoldb:/root

**Comment by PeggySchmidtMittenzwei** [comment]
**I started a bash shell with exasoldb docker environment:**
pesm@pesm-VirtualBox:~/Desktop$` docker exec -it exasoldb /bin/bash`

[root@n11 /]#  **`openssl s_client -starttls mysql -connect [172.17.0.1:3306](http://172.17.0.1:3306/) -tls1_2 -CAfile /root/ca.crt`**


**OUTPUT**


CONNECTED(00000003)
Can't use SSL_get_servername
depth=1 CN = TLS Tutorial CA, C = DE, L = Bavaria, O = Tutorial Organization
verify return:1
depth=0 CN = TLS Tutorial MySQL Server, C = DE, L = Bavaria, O = Tutorial Organization
verify return:1
---
Certificate chain
 0 s:CN = TLS Tutorial MySQL Server, C = DE, L = Bavaria, O = Tutorial Organization
   i:CN = TLS Tutorial CA, C = DE, L = Bavaria, O = Tutorial Organization
 1 s:CN = TLS Tutorial CA, C = DE, L = Bavaria, O = Tutorial Organization
   i:CN = TLS Tutorial CA, C = DE, L = Bavaria, O = Tutorial Organization
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFpzCCA4+gAwIBAgIUM6p0CM9ESoan7O+7SE5dUEWWBpcwDQYJKoZIhvcNAQEL
BQAwWTEYMBYGA1UEAwwPVExTIFR1dG9yaWFsIENBMQswCQYDVQQGEwJERTEQMA4G
A1UEBwwHQmF2YXJpYTEeMBwGA1UECgwVVHV0b3JpYWwgT3JnYW5pemF0aW9uMB4X
DTIzMDEyMTEzNTM0NloXDTIzMDQyMTEzNTM0NlowYzEiMCAGA1UEAwwZVExTIFR1
dG9yaWFsIE15U1FMIFNlcnZlcjELMAkGA1UEBhMCREUxE

**Comment by redcatbear** [comment]
Closing this ticket since requester does not remember anymore what this was about.
