### ISSUE TITLE
systemctl does not work in WSL Ubuntu env.

### ISSUE THREAD

**Issue by PeggySchmidtMittenzwei** [exasol/exasol-java-tutorial#21]
Instead of systemctl restart mysql you have to start with 
- (1) sudo service mysql start
- (2)  sudo service docker start

But before it worked I had to execute this:
for (1)
```
sudo su
nohup kill 1063; sleep 2; usermod -d /var/lib/mysql/ mysql &
```

for(2)
https://docs.docker.com/engine/install/ubuntu/

**Comment by redcatbear** [comment]
I have no Windows machine to test this. Also I unfortunately don't have enough time to test on two systems. I will add a mention that this is intended to be run on Ubuntu iron or a full-fledged Ubuntu VM.
