### ISSUE TITLE
TLS tutorial findings

### ISSUE THREAD

**Issue by allipatev** [exasol/exasol-java-tutorial#41]
**TLS in User Defined Functions (UDFs)**

- "We are going to use [curl to upload the truststore](https://docs.exasol.com/db/latest/database_concepts/bucketfs/file_access.htm#cURL) file to the default bucket." it seems that docs expects anchor in lower case: https://docs.exasol.com/db/latest/database_concepts/bucketfs/file_access.htm#curl
- "trusstore" -> "truststore"?

**TLS With Exasol**

- "For a truly secure connection, you need to put in place a custom server certificate immediately after installing **EXAOperation**.": Logically, we are talking rather about installing cluster / DB.
- "The certificate is signed by an Exasol Certification Agency (CA) and your machine does not have that CA’s certificate pre-installed": Really? For my Exasol Community Edition default certificate chain consists of only 0 level.

**Using Your Own Certificates**

- "Open SSL": an unneeded space.
- "certificate extensions.To": a space is missing.
- "This header can be used for **find** a set of options in the configuration file" -> finding?
- "information. : The key": an unneeded colon.
- "You could drop that option if you **wanted**, because this is the default for certificates." -> want?
- "**No** we are all set to install the certificates." -> Now?
- "win any **price**" -> prize?
- "/etc/mysql/mysql.conf.d/mysqld.cnf ": unneeded space is highlighted.
- "OpenSSL's **sclient**" -> s_client?
- "MySQ**l**" -> MySQ**L**?
- "Copy the driver to the default Bucket" should, probably, refer to MySQL JDBC driver, not to `tls-tutorial.jar`. Applies to the remainder of "Installing the MySQL JDBC driver in Exasol" section as well.
- Formatting right after "You are now set up and ready to run the import." is broken.

**Comment by redcatbear** [comment]
* Fixed link with `#curl` anchor
* Fixed typo in the word 'truststore'
* Replaced 'EXAOperation' with 'cluster' in one location.
* Replaced mention of preinstalled L1 certificate with self-signed
* Fixed typo in 'OpenSSL'
* Added missing space: '... extensions. To ...'
* Fixed type on 'finding'
* Colon before 'key' is a Markdown element. No change.
* Fixed 'Want' with 'could'
* Fixed typo in "Now" and added comma
* Replaced 'price' with 'prize'
* Moved misplaced space after 'mysqld.cnf'
* Fixed typo in 's_client'
* Fixed typos in 'MySQL'
* Fixed driver JAR name
* Fixed formatting
